### ISSUE TITLE
Issue with Installing optimalportfolios due to pg_config Missing in WSL2 Environment

### ISSUE THREAD

**Issue by ChoiInYeol** [ArturSepp/OptimalPortfolios#1]
Hello,

I encountered an issue while trying to install the `optimalportfolios` package using `pipenv` in a WSL2 environment. The installation process failed due to a missing `pg_config` executable, which is required by the `psycopg2` dependency.

**Environment**:
- Operating System: Windows 11 with WSL2 (Ubuntu 22.04)
- Python Version: 3.10
- pipenv

**Error Message**:
```
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-lm58kw5h/psycopg2.egg-info
      writing /tmp/pip-pip-egg-info-lm58kw5h/psycopg2.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-lm58kw5h/psycopg2.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-pip-egg-info-lm58kw5h/psycopg2.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-lm58kw5h/psycopg2.egg-info/SOURCES.txt'
      
      Error: pg_config executable not found.
      
      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:
      
          python setup.py build_ext --pg-config /path/to/pg_config build ...
      
      or with the pg_config option in 'setup.cfg'.
      
      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.
      
      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Steps to Reproduce**:
1. Create a new project with `pipenv` in WSL2.
2. Add `optimalportfolios` to `Pipfile`.
3. Run `pipenv install`.

**Resolution**:
The issue was resolved by installing PostgreSQL, which includes the `pg_config` executable. The following command was used to install PostgreSQL in WSL2:
```bash
sudo apt-get update
sudo apt-get install postgresql postgresql-contrib libpq-dev
```
After installing PostgreSQL, the `pipenv install optimalportfolios` command completed successfully.

**Suggestion**:
It would be helpful to mention this dependency in the installation documentation or provide guidance for resolving this issue in environments where `pg_config` might not be present by default.

Thank you for your attention to this matter.

**Comment by ArturSepp** [comment]
Thank you for pointing it out.
I added psycopg2 to the project requirements - I hope it will solve the installation
Pls also see the discussion here
https://stackoverflow.com/questions/11618898/pg-config-executable-not-found
It appears a problem related to Debian/Ubuntu - there are some suggestions to fix it.
Please let me know if you have any comments
